//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GraphExpImpRes.rc
//
#define IDR_MAINFRAME                   1
#define IDR_GRAPHETYPE                  2
#define IDC_TREE                        3
#define IDD_ADD_PROFILE_DIALOG          4
#define IDC_SELECT_TYPE_PROFILE         5
#define IDC_TYPE_PROFILE                6
#define IDC_CHARACTERISTICS_PROFILE     7
#define IDC_INPUT_NAME_PROFILE          8
#define IDC_NAME_PROFILE                9
#define IDC_SELECT_SECTION              10
#define IDC_SECTION                     11
#define IDC_SELECT_FOLDER               12
#define IDC_FOLDER                      13
#define IDC_OPEN_SELECT_FOLDER          14
#define IDC_PARAM_TRANS_COOR            15
#define IDC_INPUT_FACTOR_X              16
#define IDC_FACTOR_X                    17
#define IDC_INPUT_FACTOR_Y              18
#define IDC_FACTOR_Y                    19
#define IDC_INPUT_SHIFT_X               20
#define IDC_SHIFT_X                     21
#define IDC_INPUT_SHIFT_Y               22
#define IDC_SHIFT_Y                     23
#define IDC_INPUT_TURN                  24
#define IDC_TURN                        25
#define IDC_INPUT_SIZE_X                26
#define IDC_SIZE_X                      27
#define IDC_INPUT_SIZE_Y                28
#define IDC_SIZE_Y                      29
#define IDC_INITIAL_ORDER_COORDINATES   30
#define IDC_USUAL                       31
#define IDC_INVERT                      32
#define IDC_PARAMETERS_EXPORT           33
#define IDC_GRAPH_AREA                  34
#define IDC_SELECT_GRAPH_AREA_NAME      35
#define IDC_GRAPH_AREA_NAME             36
#define IDC_DESCRIPTION_PROJECTION      37
#define IDC_INPUT_DESCR_PROJECTION      38
#define IDC_UNIT                        39
#define IDC_METRE                       40
#define IDC_MILLIMETRE                  41
#define IDD_ADD_FILES_EXP_DIALOG        42
#define IDC_COMPLEMENT_CENTERS          43
#define IDC_LIST                        44
#define IDC_INPUT_QUERY                 45
#define IDC_QUERY                       46
#define IDD_ADD_FILES_IMP_DIALOG        47
#define IDC_INPUT_FILE_NAME             48
#define IDC_FILE_NAME                   49
#define IDC_OPEN_SELECT_FILE            50
#define IDC_IMPORT_LINES                51
#define IDC_SELECT_TYPE_LINES           52
#define IDC_TYPE_LINES                  53
#define IDC_BREAK_LINES_SEGMENTS        54
#define IDC_SKIP_SUPERFLUOUS_POINTS     55
#define IDC_IMPORT_TEXT                 56
#define IDC_SELECT_TYPE_TEXT            57
#define IDC_TYPE_TEXT                   58
#define IDC_CODE_TEXT                   59
#define IDC_WINDOWS                     60
#define IDC_DOS                         61
#define IDC_IMPORT_DENOTATIONS          62
#define IDC_TRANSFORM_DENOTATIONS       63
#define IDC_CIRCLES                     64
#define IDC_PRIMITIVES                  65
#define IDC_SELECT_TYPE_DENOTATIONS     66
#define IDC_TYPE_DENOTATIONS            67
#define IDC_INPUT_SIZE_DENOTATIONS      68
#define IDC_SIZE_DENOTATIONS            69
#define IDC_IMPORT_CHARAKTERISTICS      70
#define IDC_IMP_CHARAKTERISTICS         71
#define IDC_SELECT_NAME_CHARAKTERISTICS 72
#define IDC_FIELD_CHARAKTERISTICS       73
#define IDC_SELECT_TYPE_CHARAKTERISTICS 74
#define IDC_TYPE_CHARAKTERISTICS        75
#define IDC_INPUT_SIZE_CHARACTERISTICS  76
#define IDC_SIZE_CHARACTERISTICS        77
#define IDC_DELETE_GRAPH_OBJECT         78
#define IDD_ADD_SAMPLE_PROFILE_DIALOG   79
#define IDD_EDIT_FILES_EXP_DIALOG       80
#define IDD_EDIT_FILES_IMP_DIALOG       81
#define IDD_EDIT_PROFILE_EXP_DIALOG     82
#define IDD_EDIT_PROFILE_IMP_DIALOG     83
#define IDD_EDIT_PROFILE_TRANS_DIALOG   84
#define IDD_EDIT_PROFILE_REORG_DIALOG   85
#define IDD_ABOUT                       86
#define IDD_NAME_NEW_TABLE              87
#define IDC_INPUT_NAME_TABLE            88
#define IDC_NAME_TABLE                  89
#define ID_OPERATIONS_CREATE_PROFILE    90
#define ID_OPERATIONS_CREATE_FILE       91
#define ID_OPERATIONS_CREATE_SAMPLE     92
#define ID_OPERATIONS_EDIT              93
#define ID_OPERATIONS_DELETE            94
#define ID_OPERATIONS_EXECUTE           95
#define ID_PROGRAM_HELP                 96
#define ID_PROGRAM_ABOUT                97
#define IDR_TOOLBAR                     98
#define ID_CREATE_PROFILE               99
#define ID_CREATE_FILE                  100
#define ID_CREATE_SAMPLE                101
#define ID_EDIT                         102
#define ID_DELETE                       103
#define ID_EXECUTE                      104
#define ID_EXIT                         105
#define ID_OPEN_HELP                    106
#define ID_OPEN_ABOUT                   107
#define IDR_POPUP_MENU                  108
#define ID_POPUP_CREATE_PROFILE         109
#define ID_POPUP_CREATE_FILE            110
#define ID_POPUP_CREATE_SAMPLE          111
#define ID_POPUP_EDIT                   112
#define ID_POPUP_DELETE                 113
#define ID_POPUP_EXECUTE                114
#define IDS_STATUS_STRING               115
#define IDB_PICTURE_PROFILE_EXP         116
#define IDB_PICTURE_PROFILE_IMP         117
#define IDB_PICTURE_PROFILE_TRANS       118
#define IDB_PICTURE_PROFILE_REORG       119
#define IDB_PICTURE_FILE_EXP            120
#define IDB_PICTURE_FILE_IMP            121
#define IDB_PICTURE_CITY                122

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        10000
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         10003
#define _APS_NEXT_SYMED_VALUE           10000
#endif
#endif
